Repository Clubber2024/Clubber-Server, pull requests merged in 2024-12, with the labels that each got.

#517 feat : 프로메테우스 테스트
  build.gradle
  docker-compose-dev.yml
  docker-compose-local.yml
  prometheus.yml
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
Labels: Server, 🧩 dev

#518 fix : 프로메테우스 볼륨 경로 수정 (#514)
  docker-compose-dev.yml
Labels: 🐞 BugFix

#522 feat : grafana 컨테이너 추가
  docker-compose-dev.yml
Labels: Server, 🧩 dev

#525 feat : 개별 모집글 dto - 동아리명, 동아리 로고 추가
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
Labels: 🔨 Refactor, 🧩 dev

#532 feat : 도메인 별 에러케이스 swagger 통해 반환
  src/main/java/com/clubber/ClubberServer/domain/example/ExampleController.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/ApiErrorCodeExample.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/ExampleHolder.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
Labels: 📬 API, Server, 🧩 dev

#535 deploy : compose-prod 파일 수정
  docker-compose-prod.yml
Labels: 🌏 Deploy

#536 운영서버로 머지
  docker-compose-prod.yml
  src/main/java/com/clubber/ClubberServer/domain/example/ExampleController.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/ApiErrorCodeExample.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/ExampleHolder.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
Labels: 🌏 Deploy

#538 docker-compose-prod수정
  docker-compose-prod.yml
Labels: 🌏 Deploy, 🧩 dev

#539 운영서버 머지
  docker-compose-prod.yml
Labels: 🌏 Deploy

#531 refactor : 삭제된 모집글 필터링 되도록 코드 수정 (#511)
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
Labels: 🔨 Refactor, 🧩 dev

#544 refactor : transctional annotation 추가 (#533)
  src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
Labels: 🔨 Refactor, 🧩 dev
