Repository Clubber2024/Clubber-Server, pull requests merged in 2025-02, with the labels that each got.

#619 refactor : 회원 탈퇴 시 soft delete 비동기 적용
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
  src/main/java/com/clubber/ClubberServer/domain/auth/controller/AuthController.java
  src/main/java/com/clubber/ClubberServer/domain/auth/facade/UserRegisterFacade.java
  src/main/java/com/clubber/ClubberServer/domain/auth/facade/UserWithdrawFacade.java
  src/main/java/com/clubber/ClubberServer/global/common/consts/ClubberStatic.java
  src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEvent.java
  src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEventHandler.java
  src/main/java/com/clubber/ClubberServer/global/event/withdraw/SoftDeleteEventPublisher.java
Labels: 🔨 Refactor, Server

#620 refactor : 통합 테스트를 위한 설정 환경 분리
  build.gradle
  grafana-data/grafana.db
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsPasswordRequest.java
  src/main/java/com/clubber/ClubberServer/domain/common/BaseEntity.java
  src/main/java/com/clubber/ClubberServer/domain/common/controller/ExceptionController.java
  src/main/java/com/clubber/ClubberServer/domain/common/service/ExceptionService.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminReviewServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/review/service/ReviewServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
  src/test/java/com/clubber/ClubberServer/integration/util/ServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/WithMockCustomUser.java
  src/test/java/com/clubber/ClubberServer/integration/util/WithMockCustomUserSecurityContextFactory.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminReviewFixture.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/ReviewFixture.java
Labels: ✅ Test, Server

#623 feat : loki promtail 개발 서버 연동 테스트
  docker-compose-dev.yml
  src/main/resources/logback-spring.xml
Labels: ⚙ Setting, 🌏 Deploy, 🧩 dev

#625 refactor : network 추가 (#622)
  docker-compose-dev.yml
Labels: 🌏 Deploy, 🧩 dev

#629 refactor : 모집글 - 유지되는 이미지 ordernum 증가 로직 누락된 것 추가 (#628)
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
Labels: 🐞 BugFix, 🧩 dev

#630 prometheus gateway 연결
  docker-compose-dev.yml
Labels: 🌏 Deploy, 🧩 dev

#633 feat : 분과 포함 + 분과 별로 그룹핑하여 보내는 걸로 수정 (#586)
  src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetSummaryClubGroupResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetSummaryClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/repository/ClubRepository.java
  src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
Labels: ✨ Feature, 🧩 dev

#635 Feat : recruit 댓글 서비스 구현 (#618)
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitCommentController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/RecruitComment.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitComment/DeleteRecruitCommentResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitComment/GetRecruitCommentResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitComment/PostRecruitCommentRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitComment/PostRecruitCommentResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitCommentNotFoundException.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitCommentUserUnauthorizedException.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitCommentRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitCommentService.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/test/java/com/clubber/ClubberServer/integration/domain/recruitComment/controller/RecruitCommentControllerTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/recruitComment/service/RecruitCommentServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/RecruitCommentFixture.java
Labels: ✨ Feature, 🧩 dev

#637 bug : websecuritycustomizer을 이용하여 ignoring 적용
  src/main/java/com/clubber/ClubberServer/domain/review/controller/KeywordController.java
  src/main/java/com/clubber/ClubberServer/global/config/security/FilterConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/JwtTokenFilter.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
Labels: 🐞 BugFix, 🧩 dev

#641 feat : 스웨거 api 그룹화 (#640)
  src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
  src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/adminRecruitController.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
Labels: ⚙ Setting, 🧩 dev

#644 refactor : 운영 환경 별 로그 출력 수정 변경 (#631)
  src/main/resources/console-appender.xml
  src/main/resources/file-info-appender.xml
  src/main/resources/logback-spring.xml
Labels: 🔨 Refactor, Server, 🧩 dev

#648 refactor : 멀티 빌드 스테이지 적용 (#647)
  Dockerfile.nginx.dev
Labels: 🔨 Refactor, 🧩 dev

#649 refactor : 실행시 필요한 라이브러리는 유지하도록 수정 (#647)
  Dockerfile.nginx.dev
Labels: 🔨 Refactor, 🧩 dev

#651 feat : 숭실대 공식 단체 조회 api 구현 (#650)
  src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
  src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetOfficialClubGroupResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetOfficialClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
Labels: 🔨 Refactor, 🧩 dev

#653 개발 -> 운영
  Dockerfile.nginx.dev
  src/main/java/com/clubber/ClubberServer/domain/club/controller/ClubController.java
  src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetOfficialClubGroupResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetOfficialClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
Labels: 🌏 Deploy, ⭐️ main

#654 refactor : 운영서버 nginx docker file 수정 (#652)
  Dockerfile.nginx.prod
Labels: 🔨 Refactor, ⭐️ main

#656 dev -> main
  Dockerfile.nginx.prod
Labels: ⭐️ main

#658 refactor : 동아리 즐겨찾기 여부 반환 api 구현
  src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
  src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
  src/test/java/com/clubber/ClubberServer/integration/domain/favorite/service/FavoriteServiceTest.java
Labels: ✨ Feature, 🔨 Refactor, Server

#659 refactor : 회원의 즐겨찾기 여부 dto로 수정 (#657)
  src/main/java/com/clubber/ClubberServer/domain/user/controller/UserController.java
  src/main/java/com/clubber/ClubberServer/domain/user/dto/GetIsUserFavoriteResponse.java
  src/main/java/com/clubber/ClubberServer/domain/user/service/UserService.java
  src/test/java/com/clubber/ClubberServer/integration/domain/favorite/service/FavoriteServiceTest.java
Labels: 🔨 Refactor

#664 refactor : faq 수정
  src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
  src/main/java/com/clubber/ClubberServer/domain/faq/service/FaqService.java
Labels: 🔨 Refactor, Server

#667 refactor : 해시태그 - 미디어, 영화 추가 (#666)
  src/main/java/com/clubber/ClubberServer/domain/club/domain/Hashtag.java
Labels: 🔨 Refactor, 🧩 dev

#670 refactor : Division 분과 저장 순서대로 반환 (#669)
  src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
Labels: 🔨 Refactor, 🧩 dev

#674 chore : faq 수정 (#673)
  src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
Labels: 🔨 Refactor, Server

#676 Refactor/#675 : 리뷰 통계 일급 컬렉션 불변성 보장 개선
  src/main/java/com/clubber/ClubberServer/domain/review/mapper/ReviewMapper.java
  src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
  src/main/java/com/clubber/ClubberServer/domain/review/vo/KeywordStatsVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumDefaultMapperVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumFaQMapperVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumImageMapperVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumMapperVO.java
  src/test/java/com/clubber/ClubberServer/unit/domain/review/mapper/ReviewMapperTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/review/vo/ReviewKeywordVOTest.java
Labels: 🔨 Refactor, Server

#677 fix : VO 직렬화 문제 해결
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumDefaultMapperVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumFaQMapperVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumImageMapperVO.java
Labels: 🐞 BugFix, 🧩 dev

#680 refactor : 모니터링 컨테이너 분리
  docker-compose-monitory.yml
  docker-compose-prod.yml
Labels: 🌏 Deploy, Server, ⭐️ main

#686 refactor : 로그 파일명 통일 (#678)
  src/main/resources/file-info-appender.xml
Labels: ⭐️ main, 🧩 dev

#679 test: club 관련 테스트코드 작성 (#643)
  src/test/java/com/clubber/ClubberServer/integration/domain/club/controller/ClubControllerTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/club/service/ClubServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
Labels: ✅ Test, 🧩 dev

#691 docs : 기타 개행 수정 (#688)
  Readme.md
Labels: 📃 Docs

#697 refactor : 공식 단체 이름 변경 (#696)
  src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
Labels: 🔨 Refactor, 🧩 dev

#698 feat : everytimeUrl 추가 (#695)
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitResponse.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/RecruitFixture.java
Labels: 🔨 Refactor, 🧩 dev

#699 dev -> main
  src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubType.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitResponse.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/RecruitFixture.java
Labels: ⭐️ main

#701 refactor : 모집글 수정- everytimeurl 업데이트 로직 추가 (#700)
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
  src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
Labels: 🔨 Refactor, 🧩 dev

#705 refactor : faq 문구 수정 (#704)
  src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
Labels: 🔨 Refactor

#706 refactor : faq 느낌표 제거 (#704)
  src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
Labels: 🔨 Refactor

#707 dev -> main
  src/main/java/com/clubber/ClubberServer/domain/faq/domain/Faq.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
  src/test/java/com/clubber/ClubberServer/integration/domain/recruit/service/RecruitServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
Labels: ⭐️ main

#710 feat: 캘린더 api 구현(#709)
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitCalendarController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Semester.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitCalendar/GetCalendarInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitCalendar/GetCalendarResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitCalendarInvalidMonthException.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitCalendarInvalidYearException.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitCalendarService.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
Labels: ✨ Feature, 🧩 dev

#712 feat : 동아리 메일 전송 & 인증 api
  src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
  src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
  src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminEmailAuth.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminAuthResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminMailAuthRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminAuthRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminAuthResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminInvalidAuthStringException.java
  src/main/java/com/clubber/ClubberServer/domain/admin/facade/AdminEmailAuthFacade.java
  src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminEmailAuthRepository.java
  src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminRepository.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAuthService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReadService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/validator/AdminValidator.java
  src/main/java/com/clubber/ClubberServer/global/common/consts/ClubberStatic.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
  src/main/java/com/clubber/ClubberServer/global/util/RandomAuthStringGeneratorUtil.java
Labels: ✨ Feature, Server, 🧩 dev

#715 refactor: LocalDateTime으로 변경+ 밀리 초 제거 (#714)
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitCalendar/GetCalendarResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitCalendarService.java
Labels: 🔨 Refactor

#718 refactor : adminservice 분리 및 단위 테스트 작성
  src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
  src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
  src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminEmailAuth.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminAuthResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminsLoginResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminAuthRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminInvalidAuthCodeException.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminInvalidAuthStringException.java
  src/main/java/com/clubber/ClubberServer/domain/admin/facade/AdminEmailAuthFacade.java
  src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminEmailAuthRepository.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAuthService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminClubService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminEmailAuthService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReadService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/validator/AdminValidator.java
  src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/controller/AdminReviewControllerTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAccountServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAuthServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminClubServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/user/service/FavoriteServiceTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/domain/AdminDomainTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/service/AdminAccountServiceTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/service/AdminClubServiceTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/validator/AdminValidatorTest.java
Labels: 🔨 Refactor, ✅ Test, Server

#720 feat : 인터셉터를 이용한 로깅 구현
  src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
  src/main/java/com/clubber/ClubberServer/global/config/log/LogInterceptor.java
  src/main/java/com/clubber/ClubberServer/global/config/log/WebConfig.java
Labels: ✨ Feature, Server

#721 feat : 유튜브링크 추가 (#711)
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminClubService.java
  src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
  src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubInfoResponse.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
Labels: 🔨 Refactor, 🧩 dev

#725 refactor : 운영 환경 별 허용 origin pattern 분리 (#662)
  src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
Labels: 🔨 Refactor, Server

#728 dev -> main (캘린더 기능 배포)
  src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminController.java
  src/main/java/com/clubber/ClubberServer/domain/admin/domain/Admin.java
  src/main/java/com/clubber/ClubberServer/domain/admin/domain/AdminEmailAuth.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminAuthResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminMailAuthRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/CreateAdminsLoginResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminAuthRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminAuthResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageRequest.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateClubPageResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/admin/exception/AdminInvalidAuthCodeException.java
  src/main/java/com/clubber/ClubberServer/domain/admin/facade/AdminEmailAuthFacade.java
  src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminEmailAuthRepository.java
  src/main/java/com/clubber/ClubberServer/domain/admin/repository/AdminRepository.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAccountService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminAuthService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminClubService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminEmailAuthService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReadService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminService.java
  src/main/java/com/clubber/ClubberServer/domain/admin/validator/AdminValidator.java
  src/main/java/com/clubber/ClubberServer/domain/auth/service/AuthService.java
  src/main/java/com/clubber/ClubberServer/domain/club/domain/Club.java
  src/main/java/com/clubber/ClubberServer/domain/club/domain/ClubInfo.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubInfoResponse.java
  src/main/java/com/clubber/ClubberServer/domain/image/service/S3UploadPresignedService.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitCalendarController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Semester.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitCalendar/GetCalendarInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/recruitCalendar/GetCalendarResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitCalendarInvalidMonthException.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitCalendarInvalidYearException.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitCalendarService.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
  src/main/java/com/clubber/ClubberServer/global/common/consts/ClubberStatic.java
  src/main/java/com/clubber/ClubberServer/global/config/log/LogInterceptor.java
  src/main/java/com/clubber/ClubberServer/global/config/log/WebConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
  src/main/java/com/clubber/ClubberServer/global/util/RandomAuthStringGeneratorUtil.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/controller/AdminControllerTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/controller/AdminReviewControllerTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAccountServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminAuthServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/admin/service/AdminClubServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/domain/user/service/FavoriteServiceTest.java
  src/test/java/com/clubber/ClubberServer/integration/util/DatabaseCleaner.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/AdminFixture.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/domain/AdminDomainTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/service/AdminAccountServiceTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/service/AdminClubServiceTest.java
  src/test/java/com/clubber/ClubberServer/unit/domain/admin/validator/AdminValidatorTest.java
Labels: ⭐️ main
