Repository Clubber2024/Clubber-Server, pull requests merged in 2025-01, with the labels that each got.

#546 feat : docker-compose timezone 설정
  docker-compose-dev.yml
  docker-compose-prod.yml
Labels: 🌏 Deploy

#548 refactor : docker-compose-dev entrypoint 수정 (#547)
  docker-compose-dev.yml
Labels: 🌏 Deploy, 🧩 dev

#551 feat : clubType dto에 추가 (#550)
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
Labels: 🧩 dev

#553 feat : 모집글 content 앞부분만 반환 (#552)
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
Labels: ✨ Feature, 🧩 dev

#557 Refactor : docker hub 계정 변경
  docker-compose-dev.yml
  docker-compose-local.yml
  docker-compose-prod.yml
Labels: ⚙ Setting

#555 refactor : Recruit entity 필드 초기화, 생성자 매개변수 제거 (#554)
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
Labels: 🔨 Refactor, 🧩 dev

#558 dev -> prod
  docker-compose-dev.yml
  docker-compose-local.yml
  docker-compose-prod.yml
  src/main/java/com/clubber/ClubberServer/domain/club/service/ClubService.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/controller/recruitController.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/domain/Recruit.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/exception/RecruitErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
  src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
  src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
  src/main/java/com/clubber/ClubberServer/domain/user/exception/UserErrorCode.java
  src/main/java/com/clubber/ClubberServer/global/config/scheduler/SchedulerConfig.java
  src/main/java/com/clubber/ClubberServer/global/event/review/approve/ReviewApproveEvent.java
  src/main/java/com/clubber/ClubberServer/global/event/review/approve/ReviewApproveEventHandler.java
  src/main/java/com/clubber/ClubberServer/global/event/review/approve/ReviewApproveEvnetPublisher.java
Labels: 🌏 Deploy, Server, ⭐️ main

#562 refactor : configurationproperties 값 바인딩 방법 변경 (#561)
  src/main/java/com/clubber/ClubberServer/ClubberServerApplication.java
  src/main/java/com/clubber/ClubberServer/global/config/ConfigurationPropertiesConfig.java
  src/main/java/com/clubber/ClubberServer/global/properties/JwtProperties.java
  src/main/java/com/clubber/ClubberServer/global/properties/KakaoProperties.java
Labels: 🔨 Refactor, Server

#564 feat : geoip 관련 설정 (#549)
  .github/workflows/ci-cd.yml
  Dockerfile.nginx.dev
  docker-compose-dev.yml
Labels: 🧩 dev

#565 fix : 모듈 경로 재성절 (#549)
  Dockerfile.nginx.dev
Labels: 🧩 dev

#569 fix : 빌드 시 컨테이너 curl 설치 (#567)
  Dockerfile.dev
Labels: 🌏 Deploy, 🔨 Refactor, 🧩 dev

#570 refactor : github secret 통합
  .github/workflows/ci-cd.yml
Labels: 🌏 Deploy, Server, ⭐️ main, 🧩 dev

#571 refactor : key 수정 (#567)
  .github/workflows/ci-cd.yml
Labels: 🌏 Deploy, 🧩 dev

#577 Refactor : response dto - final, @Schema 추가 + 유효성 검증 추가(#566)
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/mainPage/GetOneRecruitMainPageResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/mainPage/GetRecruitsMainPageResponse.java
Labels: 🔨 Refactor, 🧩 dev

#578 Feat : recruit controller 테스트 코드 작성 - 모집글 작성 (#543)
  src/test/java/com/clubber/ClubberServer/recruit/controller/RecruitControllerTest.java
  src/test/java/com/clubber/ClubberServer/recruit/service/RecruitServiceTest.java
Labels: ✅ Test, 🧩 dev

#580 refactor : Recruit request dto - @NotNull 어노테이션 제거 (#579)
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
Labels: 🔨 Refactor, 🧩 dev

#583 refactor : club dto 에 final + schema 추가 (#581)
  src/main/java/com/clubber/ClubberServer/domain/club/dto/CollegeResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/DepartmentSmallDto.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByDivisionResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubByHashTagResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubInfoResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubIntoCardResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubPopularResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubSearchResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsByHashTagResponse.java
  src/main/java/com/clubber/ClubberServer/domain/club/dto/GetClubsSearchResponse.java
Labels: 🔨 Refactor, 🧩 dev

#588 refactor : notice dto (final, schema 추가) + mapper 구현 (#585)
  src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticeResponse.java
  src/main/java/com/clubber/ClubberServer/domain/notice/dto/GetNoticesAtMainResponse.java
  src/main/java/com/clubber/ClubberServer/domain/notice/mapper/NoticeMapper.java
  src/main/java/com/clubber/ClubberServer/domain/notice/service/NoticeService.java
  src/main/java/com/clubber/ClubberServer/domain/owner/domain/Owner.java
Labels: ✨ Feature, 🔨 Refactor, 🧩 dev

#594 feat : cicd, docker-compose, dockerfile 생성 및 수정 (#589)
  .github/workflows/ci-cd.yml
  Dockerfile.nginx.prod
  docker-compose-prod.yml
Labels: 🌏 Deploy, ✨ Feature, ✅ Test

#597 dev -> main
  docker-compose-prod.yml
Labels: 🌏 Deploy, ⭐️ main

#598 feat: 마운트 문제로 주석처리 (#589)
  docker-compose-prod.yml
Labels: 🌏 Deploy

#599 dev -> main
  docker-compose-prod.yml
Labels: ⭐️ main

#600 feat: volume 주석 해제 (#589)
  docker-compose-prod.yml
Labels: 🌏 Deploy

#601 dev -> main
  docker-compose-prod.yml
Labels: ⭐️ main

#604 feat : 재배포위해 수정
  .github/workflows/ci-cd.yml
Labels: 🌏 Deploy

#605 dev -> main
  .github/workflows/ci-cd.yml
Labels: ⭐️ main

#606 refactor : 602 refactor enable 설정 클래스 분리
  src/main/java/com/clubber/ClubberServer/ClubberServerApplication.java
  src/main/java/com/clubber/ClubberServer/global/common/consts/ClubberStatic.java
  src/main/java/com/clubber/ClubberServer/global/common/page/PageResponse.java
  src/main/java/com/clubber/ClubberServer/global/common/slice/SliceResponse.java
  src/main/java/com/clubber/ClubberServer/global/config/enums/EnumConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/feign/FeignConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/jpa/JpaAuditingConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/querydsl/QueryDslConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/redis/RedisConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/response/GlobalExceptionHandler.java
  src/main/java/com/clubber/ClubberServer/global/config/response/SuccessResponseAdvice.java
  src/main/java/com/clubber/ClubberServer/global/config/s3/ImageFileExtension.java
  src/main/java/com/clubber/ClubberServer/global/config/s3/S3Config.java
  src/main/java/com/clubber/ClubberServer/global/config/scheduler/SchedulerConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/AccessDeniedFilter.java
  src/main/java/com/clubber/ClubberServer/global/config/security/AuthDetails.java
  src/main/java/com/clubber/ClubberServer/global/config/security/CorsConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/CustomAuthenticationEntryPoint.java
  src/main/java/com/clubber/ClubberServer/global/config/security/FilterConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/JwtExceptionFilter.java
  src/main/java/com/clubber/ClubberServer/global/config/security/JwtTokenFilter.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityUtils.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/ApiErrorCodeExample.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/DisableSwaggerSecurity.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/ExampleHolder.java
  src/main/java/com/clubber/ClubberServer/global/config/swagger/SwaggerConfig.java
  src/main/java/com/clubber/ClubberServer/global/converter/EnumMapperTypeConverter.java
  src/main/java/com/clubber/ClubberServer/global/dto/AccessTokenInfo.java
  src/main/java/com/clubber/ClubberServer/global/dto/ErrorResponse.java
  src/main/java/com/clubber/ClubberServer/global/dto/SuccessResponse.java
  src/main/java/com/clubber/ClubberServer/global/event/exceptionalarm/ExceptionAlarmEvent.java
  src/main/java/com/clubber/ClubberServer/global/event/exceptionalarm/ExceptionAlarmEventPublisher.java
  src/main/java/com/clubber/ClubberServer/global/event/exceptionalarm/ExceptionDiscordAlarmEventHandler.java
  src/main/java/com/clubber/ClubberServer/global/exception/BaseErrorCode.java
  src/main/java/com/clubber/ClubberServer/global/exception/BaseException.java
  src/main/java/com/clubber/ClubberServer/global/exception/EnumTypeNotValidException.java
  src/main/java/com/clubber/ClubberServer/global/exception/ErrorReason.java
  src/main/java/com/clubber/ClubberServer/global/exception/GlobalErrorCode.java
  src/main/java/com/clubber/ClubberServer/global/helper/SpringEnvironmentHelper.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/api/oauth/client/kakao/KakaoInfoClient.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/api/oauth/client/kakao/KakaoOauthClient.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/api/oauth/config/KakaoOauthConfig.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/api/oauth/dto/kakao/KakaoTokenResponse.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/api/oauth/dto/kakao/KakaoUserInfoResponse.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/exception/client/discord/DiscordClient.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/exception/config/DiscordFeignConfig.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/exception/dto/discord/DiscordMessage.java
  src/main/java/com/clubber/ClubberServer/global/jwt/JwtTokenProvider.java
  src/main/java/com/clubber/ClubberServer/global/mapper/enums/EnumMapperType.java
  src/main/java/com/clubber/ClubberServer/global/properties/JwtProperties.java
  src/main/java/com/clubber/ClubberServer/global/properties/KakaoProperties.java
  src/main/java/com/clubber/ClubberServer/global/util/ImageUtil.java
  src/main/java/com/clubber/ClubberServer/global/util/SliceUtil.java
  src/main/java/com/clubber/ClubberServer/global/validator/enums/Enum.java
  src/main/java/com/clubber/ClubberServer/global/validator/enums/EnumValidator.java
  src/main/java/com/clubber/ClubberServer/global/validator/unique/Unique.java
  src/main/java/com/clubber/ClubberServer/global/validator/unique/UniqueConstraintValidator.java
  src/main/java/com/clubber/ClubberServer/global/vo/enums/EnumMapperVO.java
  src/main/java/com/clubber/ClubberServer/global/vo/image/ImageVO.java
Labels: ⚙ Setting, 🔨 Refactor, Server, 🧩 dev

#607 feat : 메일 전송 서비스 구현 (591)
  build.gradle
  src/main/java/com/clubber/ClubberServer/global/config/async/AsyncConfig.java
  src/main/java/com/clubber/ClubberServer/global/config/mail/MailConfig.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/mail/MailService.java
  src/main/java/com/clubber/ClubberServer/global/properties/MailProperties.java
Labels: ✨ Feature, Server

#610 bug : 리뷰 키워드 통계 오류 수정
  src/main/java/com/clubber/ClubberServer/domain/review/dto/KeywordCountStatDto.java
  src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewKeywordCustomRepositoryImpl.java
  src/main/java/com/clubber/ClubberServer/domain/review/vo/KeywordStatsVO.java
Labels: 🐞 BugFix, 🔨 Refactor, Server

#614 Feat/#592 feat 리뷰 인증 서비스 구현
  src/main/java/com/clubber/ClubberServer/domain/admin/controller/AdminReviewController.java
  src/main/java/com/clubber/ClubberServer/domain/admin/dto/UpdateAdminsReviewVerifyResponse.java
  src/main/java/com/clubber/ClubberServer/domain/admin/service/AdminReviewService.java
  src/main/java/com/clubber/ClubberServer/domain/review/controller/KeywordController.java
  src/main/java/com/clubber/ClubberServer/domain/review/controller/PerspectiveController.java
  src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
  src/main/java/com/clubber/ClubberServer/domain/review/domain/Review.java
  src/main/java/com/clubber/ClubberServer/domain/review/domain/VerifiedStatus.java
  src/main/java/com/clubber/ClubberServer/domain/review/dto/CreateClubReviewRequest.java
  src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewAlreadyVerifiedException.java
  src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewErrorCode.java
  src/main/java/com/clubber/ClubberServer/domain/review/exception/ReviewNotFoundException.java
  src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepository.java
  src/main/java/com/clubber/ClubberServer/domain/review/repository/ReviewCustomRepositoryImpl.java
  src/main/java/com/clubber/ClubberServer/domain/review/service/PerspectiveService.java
  src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
  src/main/java/com/clubber/ClubberServer/global/config/security/SecurityConfig.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/client/PerspectiveClient.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/AttributeScore.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/AttributeType.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/CreateTextAnalyzeRequest.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/CreateTextAnalyzeResponse.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/RequestedAttribute.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/Score.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/ScoreType.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/SpanScore.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/TextDto.java
  src/test/java/com/clubber/ClubberServer/integration/util/fixture/ReviewFixture.java
  src/test/java/com/clubber/ClubberServer/unit/domain/review/domain/ReviewDomainTest.java
Labels: ✨ Feature, Server

#615 refactor : 동아리 별 리뷰 조회시 승인 상태 제외
  src/main/java/com/clubber/ClubberServer/domain/review/controller/ReviewController.java
  src/main/java/com/clubber/ClubberServer/domain/review/service/ReviewService.java
  src/main/java/com/clubber/ClubberServer/global/infrastructure/outer/perspective/dto/CreateTextAnalyzeRequest.java
Labels: 🔨 Refactor, Server

#611 Feat : recruit mapper 구현 + queryDSL로 변경 (#587)
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/DeleteRecruitByIdResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitInListResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetOneRecruitWithClubResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/GetRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/PostRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitRequest.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/UpdateRecruitResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/mainPage/GetOneRecruitMainPageResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/dto/mainPage/GetRecruitsMainPageResponse.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/mapper/RecruitMapper.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitCustomRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitCustomRepositoryImpl.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitImageCustomRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitImageCustomRepositoryImpl.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitImageRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/repository/RecruitRepository.java
  src/main/java/com/clubber/ClubberServer/domain/recruit/service/RecruitService.java
Labels: ✨ Feature, 🔨 Refactor, 🧩 dev
